import { StyleSheet } from 'react-native';
import { fonts } from '../../constants/theme';

export const createStyles = (colors) =>
  StyleSheet.create({
  workoutInner: {
    flex: 1,
  },
  header: {
    marginBottom: 12,
    fontSize: 22,
    fontWeight: '500',
    fontFamily: fonts.medium,
    color: colors.text,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerButton: {
    marginBottom: 12,
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  headerButtonText: {
    color: colors.accent,
    fontWeight: '500',
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  workoutHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  finishBtn: {
    marginBottom: 12,
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  finishBtnText: {
    color: colors.accent,
    fontWeight: '500',
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  backButtonContainer: {
    marginTop: 6,
    marginBottom: 8,
    paddingVertical: 8,
  },
  backLink: {
    color: colors.accent,
    fontWeight: '500',
    fontSize: 14,
  },
  card: {
    backgroundColor: colors.card,
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  cardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  cardDuration: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '500',
  },
  cardSub: {
    color: colors.muted,
    fontSize: 11,
  },
  cardArrow: {
    color: colors.accent,
  },
  listContent: {
    paddingBottom: 120,
  },
  bottomAction: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 18,
  },
  bottomButton: {
    backgroundColor: 'transparent',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  bottomButtonText: {
    color: colors.accent,
    fontWeight: '500',
    fontFamily: fonts.medium,
    fontSize: 14,
  },
  outlineBtn: {
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: colors.accent,
    padding: 15,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: 'center',
  },
  outlineBtnText: {
    color: colors.accent,
    fontWeight: '500',
  },
  input: {
    backgroundColor: colors.card,
    color: colors.text,
    padding: 12,
    borderRadius: 12,
  },
  inputSmall: {
    backgroundColor: colors.card,
    color: colors.text,
    padding: 12,
    borderRadius: 12,
    width: 75,
    marginRight: 10,
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  addBtn: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  addBtnText: {
    fontWeight: '500',
    color: colors.accent,
  },
  setRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
    backgroundColor: colors.card,
    borderRadius: 12,
    marginBottom: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  setText: {
    color: colors.muted,
    fontWeight: '500',
  },
  setVal: {
    color: colors.text,
    fontWeight: '500',
    fontSize: 16,
  },
  removeText: {
    color: colors.error,
    fontSize: 10,
  },
  modalContent: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalHeader: {
    marginTop: 40,
    paddingHorizontal: 20,
  },
  modalBackRow: {
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  groupGridRow: {
    gap: 10,
  },
  groupListContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  groupTile: {
    flex: 1,
    aspectRatio: 1,
    backgroundColor: colors.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  groupTileSelected: {
    borderColor: colors.accent,
  },
  groupIconWrap: {
    marginBottom: 8,
    width: '60%',
    height: '60%',
  },
  groupIconImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  groupTileTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  groupTileMeta: {
    color: colors.muted,
    fontSize: 10,
    marginTop: 6,
  },
  modalRow: {
    paddingHorizontal: 20,
  },
  modalInput: {
    flex: 1,
  },
  dbList: {
    paddingHorizontal: 20,
  },
  dbItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dbItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dbItemText: {
    color: colors.text,
    fontSize: 16,
  },
  dbItemMeta: {
    color: colors.muted,
    fontSize: 12,
  },
  addSmall: {
    backgroundColor: 'transparent',
    width: 50,
    height: 50,
    marginLeft: 10,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  addSmallText: {
    fontWeight: '500',
    color: colors.accent,
    fontSize: 18,
  },
  closeBtn: {
    backgroundColor: 'transparent',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    margin: 20,
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  closeBtnText: {
    color: colors.accent,
    fontWeight: '500',
  },
});
